### ISSUE TITLE
Hebrew translation

### ISSUE THREAD

**Issue by tomer** [mozilla/tabzilla#10]
"he" : { // Locale strings for Hebrew

    // Title Strings
    titleMozilla:       "Mozilla",
    titleProducts:      "מוצרים",
    titleInnovation:    "חדשנות",
    titleGetInvolved:   "היו מעורבים",

    // Link Strings
    linkMission:        "משימה",
    linkAbout:          "אודות",
    linkProjects:       "מיזמים",
    linkSupport:        "תמיכה",
    linkMDN:            "Developer Network",
    linkFirefox:        "Firefox",
    linkThunderbird:    "Thunderbird",
    linkWebFWD:         "WebFWD",
    linkLabs:           "Labs",
    linkVolunteers:     "מתנדבים",
    linkCareers:        "קריירה",
    linkFindUs:         "מצאו אותנו",
    linkJoinUs:         "הצטרפו אלינו",
    linkWebDir:         "מדריך אתרים",

    // Locale for Firefox Flicks Promotions
    firefoxFlicks:      "פרסים גדולים! שופטים מהוליווד! סימני קריאה! 
היכנסו אל Firefox Flicks, תחרות וידאו עולמית שמטרתה לספר את סיפורנו, 
או הצביעו למועדפים עליכם!",
}

**Comment by schalkneethling** [comment]
Cleaning up. The new version of Tabzilla is static so this issue is no longer relevant. Feel free to reopen if it is still an issue.
