### ISSUE TITLE
Spanish localization

### ISSUE THREAD

**Issue by willyaranda** [mozilla/tabzilla#11]
"es" : { // Locale strings for Spanish (common)

    // Title Strings
    titleMozilla:       "Mozilla",
    titleProducts:      "Productos",
    titleInnovation:    "Innovación",
    titleGetInvolved:   "Involúcrate",

    // Link Strings
    linkMission:        "Misión",
    linkAbout:          "Acerca de",
    linkProjects:       "Proyectos",
    linkSupport:        "Asistencia",
    linkMDN:            "Developer Network",
    linkFirefox:        "Firefox",
    linkThunderbird:    "Thunderbird",
    linkWebFWD:         "WebFWD",
    linkLabs:           "Labs",
    linkVolunteers:     "Voluntarios",
    linkCareers:        "Trabajos",
    linkFindUs:         "Encuéntranos",
    linkJoinUs:         "Únete",
    linkWebDir:         "Directorio del sitio",

    // Locale for Firefox Flicks Promotions
    firefoxFlicks:      "¡Grandes premios! ¡Un jurado de estrellas de Hollywood! ¡Participa en Firefox Flicks, el concurso mundial de vídeos para contar nuestra historia, o vota a tus favoritos!",
 }

**Comment by schalkneethling** [comment]
Cleaning up. The new version of Tabzilla is static so this issue is no longer relevant. Feel free to reopen if it is still an issue.
