### ISSUE TITLE
Chinese Traditional (Taiwan) Localization

### ISSUE THREAD

**Issue by petercpg** [mozilla/tabzilla#12]
"zh-TW" : { // Locale strings for Chinese Traditional (Taiwan)

    // Title Strings
    titleMozilla:       "Mozilla",
    titleProducts:      "產品",
    titleInnovation:    "創新",
    titleGetInvolved:   "參與其中",

    // Link Strings
    linkMission:        "使命",
    linkAbout:          "關於",
    linkProjects:       "專案",
    linkSupport:        "技術資源",
    linkMDN:            "開發者網路",
    linkFirefox:        "Firefox",
    linkThunderbird:    "Thunderbird",
    linkWebFWD:         "WebFWD",
    linkLabs:           "實驗室",
    linkVolunteers:     "志工",
    linkCareers:        "工作機會",
    linkFindUs:         "尋找我們",
    linkJoinUs:         "加入我們",
    linkWebDir:         "網站目錄",

    // Locale for Firefox Flicks Promotions
    firefoxFlicks:      "超棒的大獎、好萊塢評審、讓眾人驚嘆！
			請參加 Firefox Flicks，一個讓您述說我
			們故事的全球性短片競賽。您也可以參加
			投出您最愛的短片！",
}

**Comment by schalkneethling** [comment]
Cleaning up. The new version of Tabzilla is static so this issue is no longer relevant. Feel free to reopen if it is still an issue.
