### ISSUE TITLE
Dutch (nl) translation

### ISSUE THREAD

**Issue by Fjoerfoks** [mozilla/tabzilla#15]
"nl" : { // Locale strings for Dutch

    // Title Strings
    titleMozilla:       "Mozilla",
    titleProducts:      "Producten",
    titleInnovation:    "Innovatie",
    titleGetInvolved:   "Doe mee",

    // Link Strings
    linkMission:        "Missie",
    linkAbout:          "Over",
    linkProjects:       "Projecten",
    linkSupport:        "Support",
    linkMDN:            "Ontwikkelaarsnetwerk",
    linkFirefox:        "Firefox",
    linkThunderbird:    "Thunderbird",
    linkWebFWD:         "WebFWD",
    linkLabs:           "Labs",
    linkVolunteers:     "Vrijwilligers",
    linkCareers:        "Vacatures",
    linkFindUs:         "Vind ons",
    linkJoinUs:         "Meedoen",
    linkWebDir:         "Website overzicht",

    // Locale for Firefox Flicks Promotions
    firefoxFlicks:      "Grote prijzen! Hollywood
        jury! Uitroeptekens! Bekijk Firefox
        Flicks, de wereldwijde videowedstrijd om ons
        verhaal te vertellen, of stem op uw favoriet!",
}

**Comment by schalkneethling** [comment]
Cleaning up. The new version of Tabzilla is static so this issue is no longer relevant. Feel free to reopen if it is still an issue.
