### ISSUE TITLE
Frisian (fy-NL) translation

### ISSUE THREAD

**Issue by Fjoerfoks** [mozilla/tabzilla#16]
"fy-NL" : { // Locale strings for Frisian

    // Title Strings
    titleMozilla:       "Mozilla",
    titleProducts:      "Produkten",
    titleInnovation:    "Ynnovaasje",
    titleGetInvolved:   "Doch mei",

    // Link Strings
    linkMission:        "Missy",
    linkAbout:          "Oer",
    linkProjects:       "Projekten",
    linkSupport:        "Stipe",
    linkMDN:            "Untwikkelersnetwurk",
    linkFirefox:        "Firefox",
    linkThunderbird:    "Thunderbird",
    linkWebFWD:         "WebFWD",
    linkLabs:           "Labs",
    linkVolunteers:     "Frijwilligers",
    linkCareers:        "Fakatueres",
    linkFindUs:         "Fyn ús",
    linkJoinUs:         "Meidwaan",
    linkWebDir:         "Website oersjoch",

    // Locale for Firefox Flicks Promotions
    firefoxFlicks:      "Grutte prizen! Hollywood
        sjuery! Utroptekens! Besjoch Firefox
        Flicks, de wrâldwide fideowedstryd om ús
        ferhaal te fertellen, of stim op jo favoryt!",
}

**Comment by schalkneethling** [comment]
Cleaning up. The new version of Tabzilla is static so this issue is no longer relevant. Feel free to reopen if it is still an issue.
