### ISSUE TITLE
Tabzilla should be in RTL for selected languages

### ISSUE THREAD

**Issue by tomer** [mozilla/tabzilla#17]
In issue #2 we've hardcoded Tabzilla with dir=ltr in order to make sure the tab won't be affected by the page direction. 

Now, when we have support for multiple locales (issue #9), we should redesign the tab so it would be possible to use it on RTL without breaking the display of LTR locales on RTL content pages by reverting the previous hardcoded fix. 

By doing so, we should need the following changes: 
• Every locale should define its direction, as we are doing in Firefox itself by the &locale.dir; entity. This is important because we need to make sure that LTR locales, such as English, French etc. will be displayed well on RTL pages as well as LTR pages. 
• We should decide what should be flipped on RTL locale tabs. The easiest way is to mirror everything, but by doing so we will end up with some usability problems as the locale picker, for example, would be switched to the other side of the page, so if people will switch to an RTL language by mistake they might be unable to locate the language picker again in order to switch back. 
• We should add a display class to RTL which would be applied after we switch locales.

**Comment by schalkneethling** [comment]
Cleaning up. The new version of Tabzilla is static so this issue is no longer relevant. Feel free to reopen if it is still an issue.
