### ISSUE TITLE
Serbian (sr) translation

### ISSUE THREAD

**Issue by ioskar** [mozilla/tabzilla#18]
"sr" : { // Locale strings for Serbian

    // Title Strings
    titleMozilla:       "Мозила",
    titleProducts:      "Производи",
    titleInnovation:    "Иновације",
    titleGetInvolved:   "Прикључите се",

    // Link Strings
    linkMission:        "Мисија",
    linkAbout:          "О нама",
    linkProjects:       "Пројекти",
    linkSupport:        "Подршка",
    linkMDN:            "Програмерска мрежа",
    linkFirefox:        "Фајерфокс",
    linkThunderbird:    "Тандерберд",
    linkWebFWD:         "ВебФВД",
    linkLabs:           "Лабораторија",
    linkVolunteer:      "Волонтирајте",
    linkCareers:        "Запослење",
    linkFindUs:         "Нађите нас",
    linkJoinUs:         "Прикључите се",
    linkWebDir:         "Директоријум сајтова",

    // Locale for Firefox Flicks Promotions
    firefoxFlicks:      "Супер награде! Холивудске
        судије! Прикључите се Фајерфокс Фликс такмичењу
        и покажите свету Вашу причу, или 
        гласајте за Ваш омиљени видео!",
}

**Comment by schalkneethling** [comment]
Cleaning up. The new version of Tabzilla is static so this issue is no longer relevant. Feel free to reopen if it is still an issue.
