### ISSUE TITLE
Slovenian (sl) localization

### ISSUE THREAD

**Issue by mathjazz** [mozilla/tabzilla#21]
"en" : { // Locale strings for Slovenian

    // Title Strings
    titleMozilla:       "Mozilla",
    titleProducts:      "Izdelki",
    titleInnovation:    "Inovacije",
    titleGetInvolved:   "Sodelujte",

    // Link Strings
    linkMission:        "Poslanstvo",
    linkAbout:          "Predstavitev",
    linkProjects:       "Projekti",
    linkSupport:        "Podpora",
    linkMDN:            "Za razvijalce",
    linkFirefox:        "Firefox",
    linkThunderbird:    "Thunderbird",
    linkWebFWD:         "WebFWD",
    linkLabs:           "Labs",
    linkVolunteer:      "Prostovoljci",
    linkCareers:        "Zaposlitev",
    linkFindUs:         "Kje smo?",
    linkJoinUs:         "Pridružite se",
    linkWebDir:         "Imenik strani",

    // Locale for Firefox Flicks Promotions
    firefoxFlicks:      "Lepe nagrade! Sodniki 
        iz Hollywooda! Klicaji! Sodelujte v Firefox Flicks,
        svetovnem nagradnem tekmovanju,
        s svojo zgodbo ali glasujte za svoje favorite!",
}

**Comment by schalkneethling** [comment]
Cleaning up. The new version of Tabzilla is static so this issue is no longer relevant. Feel free to reopen if it is still an issue.
