### ISSUE TITLE
moz-box-sizing breaks tabzilla promo

### ISSUE THREAD

**Issue by ghost** [mozilla/tabzilla#24]
On the webfwd site the * { -moz-box-sizing: border-box; } rule is set and this causes the tabzilla promo to display it's contents incorrectly i.e. the height collapses to 130px and causes the text to overlap the image. https://webfwd.org/

**Comment by schalkneethling** [comment]
Cleaning up. The new version of Tabzilla is static so this issue is no longer relevant.
