### ISSUE TITLE
Version numbering of the whole (or parts) of tabzilla

### ISSUE THREAD

**Issue by peterbe** [mozilla/tabzilla#26]
In conjunction with my work on https://github.com/mozilla/tabzilla/pull/25 I think it would be awesome if we could start versioning tabzilla as a whole. 

I suspect most Mozilla sites that will reference the minified version (which will soon hopefully live on a snappy CDN) will use the "latest" version but for those who want optimal speed (i.e. cache-control = max) will want to use a version numbered URL. Like google does: http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js

**Comment by schalkneethling** [comment]
Cleaning up. The new version of Tabzilla is static so this issue is no longer relevant.
