### ISSUE TITLE
508/ADA Compliance

### ISSUE THREAD

**Issue by crasx** [mozilla/tabzilla#28]
Is there any plan to make tabzilla disability friendly? I noticed that on most mozilla websites there is no link to skip over the banner and special needs users are forced to tab through the menu on every page.
See: [Techniques for WCAG 2.0 G1 ](http://www.w3.org/TR/WCAG20-TECHS/G1.html)

**Comment by schalkneethling** [comment]
Cleaning up. The new version of Tabzilla is static so this issue is no longer relevant.
