### ISSUE TITLE
French localisation (fr)

### ISSUE THREAD

**Issue by PetiPandaRou** [mozilla/tabzilla#31]
"fr" : { // Locale strings for French (common)

// Title Strings
titleMozilla:       "Mozilla",
titleProducts:      "Produits",
titleInnovation:    "Innovations",
titleGetInvolved:   "Contribuer",

// Link Strings
linkMission:        "Mission",
linkAbout:          "À propos",
linkProjects:       "Projets",
linkSupport:        "Support",
linkMDN:            "Developer Network",
linkFirefox:        "Firefox",
linkThunderbird:    "Thunderbird",
linkWebFWD:         "WebFWD",
linkLabs:           "Labs",
linkVolunteers:     "Contribuer",
linkCareers:        "Carrière",
linkFindUs:         "Nous trouver",
linkJoinUs:         "Nous contacter",
linkWebDir:         "Plan du site",

// Locale for Firefox Beta Promotions
firefoxBeta:      "Téléchargez Firefox Beta, faites nous part de vos remarques et aidez nous à améliorer la prochaine version de Firefox",

}

**Comment by schalkneethling** [comment]
Cleaning up. The new version of Tabzilla is static so this issue is no longer relevant.
