### ISSUE TITLE
Malay (ms) Translation

### ISSUE THREAD

**Issue by syafiqmazli** [mozilla/tabzilla#36]
"ms" : { // Locale strings for Bahasa Malaysia / Malay

// Title Strings
titleMozilla: "Mozilla",
titleProducts: "Produk",
titleInnovation: "Innovasi",
titleGetInvolved: "Ayuh Bergabung!",

// Link Strings
linkMission: "Misi",
linkAbout: "Tentang Kami",
linkProjects: "Projek",
linkSupport: "Sokongan",
linkMDN: "Developer Network",
linkFirefox: "Firefox",
linkThunderbird: "Thunderbird",
linkWebFWD: "WebFWD",
linkLabs: "Labs",
linkVolunteers: "Sukarelawan",
linkCareers: "Kareer",
linkFindUs: "Cari Kami",
linkJoinUs: "Sertai Kami",
linkWebDir: "Peta Laman",

// Locale for Firefox Beta Promotions
firefoxBeta: "Muat turun Firefox Beta, berikan maklum balas dan bantu untuk menjadikan versi daripada Firefox malah lebih hebat!",

}

**Comment by schalkneethling** [comment]
Cleaning up. The new version of Tabzilla is static so this issue is no longer relevant.
