### ISSUE TITLE
Bahasa Indonesia [id] Translation

### ISSUE THREAD

**Issue by fauzanalfi** [mozilla/tabzilla#38]
"id" : { // Locale strings for Bahasa Indonesia

// Title Strings
titleMozilla: "Mozilla",
titleProducts: "Produk",
titleInnovation: "Inovasi",
titleGetInvolved: "Ikut Berperan",

// Link Strings
linkMission: "Misi",
linkAbout: "Tentang Kami",
linkProjects: "Proyek",
linkSupport: "Dukungan",
linkMDN: "Jaringan Pengembang",
linkFirefox: "Firefox",
linkThunderbird: "Thunderbird",
linkWebFWD: "WebFWD",
linkLabs: "Labs",
linkVolunteers: "Sukarelawan",
linkCareers: "Karier",
linkFindUs: "Temukan Kami",
linkJoinUs: "Bergabung Dengan Kami",
linkWebDir: "Direktori Situs Web",

// Locale for Firefox Beta Promotions
firefoxBeta: "Unduh Firefox Beta, berikan umpan balik dan bantu kami untuk menjadikan Firefox lebih baik!",

}

**Comment by schalkneethling** [comment]
Cleaning up. The new version of Tabzilla is static so this issue is no longer relevant.

**Comment by schalkneethling** [comment]
Cleaning up. The new version of Tabzilla is static so this issue is no longer relevant.
