### ISSUE TITLE
Improve accessibility

### ISSUE THREAD

**Issue by nukeador** [mozilla/tabzilla#4]
Reporting this in one of our Mozilla Hispano web developers behalf:

To improve Tabzilla accessibility I think it's important to separate the content (html) from the logic (js), so I propose a modification that won't embed the html via javascript.

Maybe having a service from http://www.mozilla.org/tabzilla/media/content.en.html that returns the content served now via js, that content would be used by community sites, using  a cron or other ways to retrieve an updated copy which includes the html.

This way will also help to have the content localized for each language (content.es.html, content.fr.html...)

**Comment by schalkneethling** [comment]
Cleaning up. The new version of Tabzilla is static so this issue is no longer relevant. Feel free to reopen if it is still an issue.
