### ISSUE TITLE
Macedonian (mk) translation

### ISSUE THREAD

**Issue by gocemitevski** [mozilla/tabzilla#51]
"en" : { // Locale strings for English

    // Title Strings
    titleMozilla:       "Mozilla",
    titleProducts:      "Производи",
    titleInnovation:    "Иновација",
    titleGetInvolved:   "Приклучете се",

    // Link Strings
    linkMission:        "Мисија",
    linkAbout:          "За нас",
    linkProjects:       "Проекти",
    linkSupport:        "Поддршка",
    linkMDN:            "Мрежа на развивачи",
    linkFirefox:        "Firefox",
    linkThunderbird:    "Thunderbird",
    linkWebFWD:         "WebFWD",
    linkLabs:           "Labs",
    linkWebmaker:       "Webmaker"
    linkVolunteer:      "Волонтирање",
    linkCareers:        "Вработување",
    linkFindUs:         "Пронајдете нè",
    linkJoinUs:         "Приклучете се",
    linkWebDir:         "Веб-директориум",

    // Locale for the Promotional Contents
    promoLink:          "Преземете го Firefox Beta, споделете искуства и помогнете следната верзија на Firefox да биде уште подобра."
},

**Comment by schalkneethling** [comment]
Cleaning up. The new version of Tabzilla is static so this issue is no longer relevant.
