### ISSUE TITLE
min-resolution is not supported by IE or Safari

### ISSUE THREAD

**Issue by groovecoder** [mozilla/tabzilla#62]
As [reported by the MDN compatibility service on our Pull Request to implement the new tabzilla](https://github.com/mozilla/kuma/pull/3373#discussion_r35720306), the media queries resolution feature [in `lib.less`](https://github.com/mozilla/tabzilla/blob/master/less/lib/lib.less#L19) is not supported by IE or Safari.

**Comment by alexgibson** [comment]
Thanks, Luke!

Safari uses the non-standard `device-pixel-ratio` property, so this should be fine as-is. If it does ever switch to support `min-resolution`, it should naturally pick up the change here too. Not sure about IE, but seeing as this is a CSS media query it will just fall back to the low-res version if not supported (progressive enhancement for the win!).

**Comment by groovecoder** [comment]
Heh, you sounds [just like @stephaniehobson](https://github.com/mozilla/kuma/pull/3373#discussion_r35821358). You front-end devs are too smart, you know that?
