### ISSUE TITLE
publish to npm?

### ISSUE THREAD

**Issue by Pomax** [mozilla/tabzilla#63]
Bower is mighty useful, but for those of us whose sites are predominantly deployed as node packages, it would be mighty useful if there was also an npmjs.org entry for tabzilla. That basically requires a `package.json` file (which can be initialized with the handy `npm init` command and then interactively filling out all the relevant bits) and having someone call `npm publish` after that package.json has been created, with a reissue of `npm publish` every time the current version updates.

**Comment by schalkneethling** [comment]
Thanks @Pomax, that sounds like a great idea to me.

**Comment by pdehaan** [comment]
Yes please! Currently we're bringing this into our project by including this in our package.json dependencies, which doesn't seem ideal:

```json
"mozilla-tabzilla": "mozilla/tabzilla#v0.3.0",
```

**Comment by schalkneethling** [comment]
This has been resolved in https://github.com/mozilla/tabzilla/commit/fcc52101d4df037f447006aa4cfcecda1aac7c1d

**Comment by pdehaan** [comment]
https://www.npmjs.com/package/mozilla-tabzilla AWESOME!

**Comment by Pomax** [comment]
:boom:

many thanks!
