### ISSUE TITLE
Publish v0.5.0 to npm

### ISSUE THREAD

**Issue by pdehaan** [mozilla/tabzilla#77]
I think the most recent published version of [**mozilla-tabzilla**](https://www.npmjs.com/package/mozilla-tabzilla) is 0.4.0:

```sh
$ npm i mozilla-tabzilla@latest -S
mozilla-tabzilla@0.4.0 node_modules/mozilla-tabzilla
```

https://github.com/mozilla/tabzilla/releases shows the latest version as v0.5.0 (which includes Sass support).

**Comment by schalkneethling** [comment]
This slipped through the cracks :disappointed:

**Comment by schalkneethling** [comment]
Done o/\o
