### ISSUE TITLE
HTTP ERROR 500 after update plugin!

### ISSUE THREAD

**Issue by greenpro1** [mozilla/tabzilla#83]
Every time  I try to access (forexample) mywebsite.com.au/wp-admin it gives me the following message. I have cleared website history and reinstalled Chrome.  

The mywesbite .com.au page isn’t working

mywebsite.com.au is currently unable to handle this request.
HTTP ERROR 500

this only happened after I finished updating your plugin on wordpress! please help

**Comment by alexgibson** [comment]
I think you have the wrong repo.

**Comment by greenpro1** [comment]
i dont know what that means - but i cant login to my wordpress

**Comment by pdehaan** [comment]
@greenpro1 I think @alexgibson was saying that this repo isn't a WordPress plugin, and it's very unlikely we'd be the cause of your site/admin no longer working (I'd argue that it's impossible we'd be the cause).

An HTTP 500 error sounds like a problem with your server config. You may need to check your server logs or contact your hosting company and try and find out exactly which WordPress plugin caused the breakage and then FTP in and delete/reinstall the plugin.
