### ISSUE TITLE
Should this repo be deprecated?

### ISSUE THREAD

**Issue by alexgibson** [mozilla/tabzilla#87]
We discussed this a bit in #85, but now that the new brand guidelines don't allow the mozilla wordmark being placed inside a container (such as the curved Tabzilla tab), updating this repo with the new wordmark might be slightly redundant. Sites can just include the wordmark where appropriate according to the guidelines, and it might not make sense to have a shared piece of CSS defining where it appears as navigation also varies site to site.

Thoughts @craigcook @jpetto @pmac ?

I feel like we should probably make some kind of decision here soon, to at least provide some sort of guidance as to what people should do.

**Comment by pmac** [comment]
I agree. It seems having a common UI element across our sites is no longer a desire for brand, but perhaps this decision should have their input. Fully agreed that we should provide some guidance here and soon.

/cc @bensternthal

**Comment by jpetto** [comment]
+1 to deprecating this repo. I don't see any sense in creating shared CSS for what's essentially an `<a>` tag and an image.

We could move the current contents of `README.md` to `about.md` (or whatever), then write a notice about deprecation along with suggested next steps, which could perhaps be as simple as "put a link on your site wrapping this image".

Not a bad idea to ask the brand team for their input on what users of this repo should do going forward.

**Comment by alexgibson** [comment]
I also filed a bug today to discuss ending support of the old Tabzilla, which is still being served from bedrock: https://bugzilla.mozilla.org/show_bug.cgi?id=1388296

**Comment by alexgibson** [comment]
Came across this issue today when going through some very old notifications :)

Tabzilla is long gone in terms of code, and I think brand-wise we've moved on sufficiently from this concept. [Protcol](https://protocol.mozilla.org/) now exists, and features a totally new navigation that incorporates the Mozilla wordmark.

Can we now safely deprecate this repo? GitHub also has a handy archive feature, that will lock this repo down as read-only for posterity.

**Comment by craigcook** [comment]
Let's do it!
